apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    tier: nginx-container
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: nginx-container
  template:
    metadata:
      labels:
        tier: nginx-container
    spec:
      containers:
      - name: myapp-container #container name
        image: nginx # image name
        ports:
        - containerPort: 80
