apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment-service
spec:
  selector:   
    tier: nginx-container
  type: NodePort 
  ports:
  - nodePort: 31440
    port: 80 #mandatory
    targetPort: 80 #container port
